[package]
name = "verify_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
types-2048.workspace = true
atrium-repo = "0.1.4"
atrium-crypto = "0.1.2"
atrium-api.workspace = true
sha2 = "0.11.0-rc.0"
cid = "0.11.1"
multihash = "0.19.1"
ipld-core = "0.4.1"
serde_ipld_dagcbor = { version = "0.6.0", default-features = false, features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio.workspace = true
serde_bytes = "0.11.9"
