[package]
name = "admin_2048"
version = "0.1.0"
edition = "2024"

[dependencies]
types-2048 = { path = "../types_2048" }
clap = { version = "4.5.37", features = ["derive"] }
tokio.workspace = true
anyhow.workspace = true
atrium-api.workspace = true
atrium-common.workspace = true
atrium-identity.workspace = true
atrium-xrpc-client.workspace = true
atrium-oauth.workspace = true
env_logger.workspace = true
log.workspace = true
dotenv.workspace = true
hickory-resolver = "0.24.1"
twothousand-forty-eight.workspace = true

backend_shared.workspace = true